---
# file: roles/common/tasks/main.yml
- name: Add docker apt keys
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
- name: Update apt
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present
- name: Install Docker
  apt: name=linux-image-generic-lts-trusty state=present
